### PR TITLE
Make the created statefulset have the new reconciled solr cloud status

### PR DESCRIPTION
**Pull request by timterle**
Signed-off-by: Tim Terlegård <tim.terlegard@infomaker.se>

*Issue number of the reported bug or feature request: #46*

**Describe your changes**
Changed the GenerateStatefulSet function to accept the reconciled zk status as an argument. The zk status may be incorrect in the solrCloud argument.

**Testing performed**
Tested this change in a custom operator. Solr pods start up fine.

### CODE REVIEW

**Comment by timterle** [comment]
@HoustonPutman @sepulworld  Do you understand why the test fails? The code change in feature/invalid-zkhost-in-statefulset is tiny and should not make the test fail like this.

**Comment by sepulworld** [comment]
It is probably flakey TravisCI environment. If the `make test` works locally, then probably a re-run of the failed job in TravisCI will complete successfully.

**Comment by HoustonPutman** [comment]
this is a great change that I am actually running into now. Thanks for finding the issue.

Let me re-run the tests.

**Comment by HoustonPutman** [comment]
Ok, so the tests aren't failing. It's the manifests generation, which is even weirder. I say let's just wait till #38 is merged, and then rebase this and see if the issues are fixed.

**Comment by HoustonPutman** [comment]
@timterle have you given maintainers permissions to commit to your branch? I did a merge and wanted to push it, then squash into master. But it looks like I can't.

Also this is a good change to make, but I think that the issue that exposed this won't happen anymore, as the operator waits to create the stateful set till the individual node services have been created. But this is the right implementation anyways.

**Comment by timterle** [comment]
@HoustonPutman You're right, I didn't give anyone any permissions. Looks like you managed to merge it anyways. 👍

**Pull request merged**
