### PR TITLE
Adding configurable SOLR_OPTS, GC_TUNE, logging

### PR DESCRIPTION
**Pull request by sepulworld**
Signed-off-by: Zane Williamson <zanew@zillow.com>

*Issue number of the reported bug or feature request: https://github.com/bloomberg/solr-operator/issues/32

**Describe your changes**
Allow for optional adjustment of the SOLR_OPTS and GC_TUNE environment variables, provide example. Match up with current default behavior.

Allow for tunable logging

**Testing performed**
Local and development environment testing performed to ensure Solr on 8.2.0 applies the requested parameter changes.

### CODE REVIEW

**Comment by sepulworld** [comment]
This will probably conflict with the other open PR, but merge conflict should be easy to address.

**Comment by sepulworld** [comment]
Nice, no merge conflicts with this! 👍let me know if you want to make any changes. We have vetted this change out in our environments and all is well.

**Comment by HoustonPutman** [comment]
Something weird is happening with the tests. I re-ran them at least 5 times and they didn't pass once. But it doesn't look like it has anything to do with your changes...

I'll look into it a bit more

**Comment by sepulworld** [comment]
I was looking at this too. The tests appear to spawn a couple processes (etcd for some K8s related functional tests). Perhaps they are resource starved in the container Travis is running?

**Comment by HoustonPutman** [comment]
Think that I found the issue. I believe that the other branch failing was a red herring, as that had to do with a travisCI problem. Hope you don't mind me adding the commit. If you do, I'll hold off in the future and just let you know what I find!

**Comment by HoustonPutman** [comment]
It passes! I'll merge it once you sign off on the changes!

**Comment by sepulworld** [comment]
> It passes! I'll merge it once you sign off on the changes @sepulworld !

LGTM! Ty!

**Pull request merged**
