### PR TITLE
Adding solrcollection crd

### PR DESCRIPTION
**Pull request by sepulworld**
*Issue number of the reported bug or feature request: #7 *

Describe your changes
DONE:

Added a CRD kind for SolrCloudCollections creation
Finalizer for deleting a collection
Support basic configs for both implicit and compositeId router names
Support autoAddReplica
Support basic modifications

Testing performed
DONE:
Local k8s on Docker for Mac, tested collection creation
Tested deletion of collection
Tested creation and modification of collections

### CODE REVIEW

**Comment by sepulworld** [comment]
Hi @HoustonPutman! So, I did my best to rebase with master with this PR. Hopefully it is ok.

I was able to get the take in your feedback about using the Reconcile Requeue and it works as expected now. Did some local testing and testing in our development environment.

For now, we will talk to the Solr API to check on state of things (for modifications and existence of collections). In the future you mentioned we should look into starting a ZkStateReader package for this project to cutdown on Solr API requests. 👍

**Comment by HoustonPutman** [comment]
Hey @sepulworld, I appreciate all of the effort you've put into this and it looks really good!

I have one question before merging though. I notice that you have a required `action` field in your `SolrCollection` CRD, but I don't see it provided in your examples. Should it be marked optional?

Actually looking through the code, it doesn't seem like you actually use the variable. Is it left over from some other implementation you were trying?

Other than that, I am ready to merge this though! Great work

**Comment by sepulworld** [comment]
> Hey @sepulworld, I appreciate all of the effort you've put into this and it looks really good!
> 

No problem! Thanks for starting such a rock solid operator! :)

> I have one question before merging though. I notice that you have a required `action` field in your `SolrCollection` CRD, but I don't see it provided in your examples. Should it be marked optional?
> 
> Actually looking through the code, it doesn't seem like you actually use the variable. Is it left over from some other implementation you were trying?
> 

Good catch! Removed, tested locally and looks good

> Other than that, I am ready to merge this though! Great work

**Comment by sepulworld** [comment]
Odd, https://travis-ci.com/bloomberg/solr-operator/jobs/239051532 failed, but tests fine locally. Perhaps rerun it?

**Comment by HoustonPutman** [comment]
Restarted it, looks like a one-off weirdness

**Pull request merged**
