### PR TITLE
Making java memory configurable

### PR DESCRIPTION
**Pull request by sepulworld**
Signed-off-by: Zane Williamson <zanew@zillow.com>

**Describe your changes**
Remove hardcoded memory allocation, and give ability to update jvm parameter.

**Testing performed**
Tested locally with solrcloud 8.2
Tested to verify present hardcoded value works as default

Screen Shot 2019-09-24 at 7 09 15 PM

### CODE REVIEW

**Comment by HoustonPutman** [comment]
Great addition.

**Comment by HoustonPutman** [comment]
I'm gonna wait to merge this till after we merge the Collections PR, so that you don't have to even think about rebasing that one again!

**Comment by sepulworld** [comment]
> I'm gonna wait to merge this till after we merge the Collections PR, so that you don't have to even think about rebasing that one again!

Thanks! sounds like a plan.

**Comment by sepulworld** [comment]
Also @swarupdonepudi and I started a public Slack Team for the project, hope you are cool with that? 

https://join.slack.com/t/solr-operator/shared_invite/enQtNzY3MTUyMDAxNTY5LTAxNzJiMmZhYjhkOGM1NDdjYWUyMmRkMmE1M2M1Njg2M2MzODFjZDA1ZmViNzM2YTBiYjIwMzQzZWU3YzJhMTQ

Perhaps later we can see about moving to the K8s slack team

**Comment by HoustonPutman** [comment]
Hey @sepulworld , sorry for the delay. Just got back to having internet access. I was ready to merge this, but noticed that you merged in the changes from #26 as well, which I have a few comments for. If you remove those changes, and just keep the memory ones I'll merge it! I'll make my comments on the other PR for you as well, so we can get that merged soon too

**Comment by sepulworld** [comment]
Oy, looks like my branch was configured to merge updates in automatically. Im closing this for new patch. https://github.com/bloomberg/solr-operator/pull/27

**Pull request closed without merging**
