### PR TITLE
solr-operator Helm chart

### PR DESCRIPTION
**Pull request by kcmartin**
Signed-off-by: Kristin Martin <kcmartin2@mac.com>

*Issue number of the reported bug or feature request: #20 

**Describe your changes**
Adding Helm chart to install solr-operator.
For now, this lives within the solr-operator repo.

**Testing performed**
I tested installation on a local dev cluster, and on one of our dev clusters in AWS

Tested installation and removal using both Helm 2 and Helm 3, see notes README regarding CRD handling in Helm 2 vs. 3

**Additional context**
@swarupdonepudi mentions we will need to add RBAC to the chart, so I would like to get feedback from @HoustonPutman and @sepulworld regarding this.

Thank you!

### CODE REVIEW

**Comment by HoustonPutman** [comment]
Thanks for the addition kristin! I'm not very knowledgable about Helm at all, but I will try to learn as I review this. Sorry if this takes some time though. I'll probably have more than a few questions.

**Comment by kcmartin** [comment]
Thanks @HoustonPutman! 

We also have @sepulworld and @swarupdonepudi on the team to assist with Helm-related questions.

I'll circle back with them about adding the RBAC rules.

One more note, It looks like the Travis build is failing due to `kustomize` being missing as a dependency, is that something I should add to https://github.com/bloomberg/solr-operator/blob/master/hack/install_dependencies.sh ?

**Comment by HoustonPutman** [comment]
Yeah, for kustomize that's the right way to go.

I'd use the `install` method mentioned here: https://github.com/kubernetes-sigs/kustomize/blob/master/docs/INSTALL.md#try-go

**Comment by kcmartin** [comment]
I'm going to go ahead and close this PR, in favor of a new one that is cleaner and doesn't include weird merges :)

**Pull request closed without merging**
