### PR TITLE
Fix links in README.md

### PR DESCRIPTION
**Pull request by dalbani**
**Describe your changes**
Minor fix of links in README.md.

**Testing performed**
N/A

**Additional context**
N/A

### CODE REVIEW

**Comment by dalbani** [comment]
The part with `Have you had a good experience with <project>?` should probably also be updated to mention the project's name.

**Comment by HoustonPutman** [comment]
Good catch, would you mind updating that in your PR as well?

**Comment by dalbani** [comment]
What name should I use then? Simply:
"Have you had a good experience with the **Solr Operator**?"

**Comment by bsankara** [comment]
Thank you for this contribution -- can you also sign off on the contribution terms per https://github.com/bloomberg/.github/blob/master/CONTRIBUTING.md#contribution-licensing

**Pull request merged**
